add retry

diff --git a/hooks/checkout b/hooks/checkout
--- a/hooks/checkout
+++ b/hooks/checkout
@@ -107,6 +107,8 @@ checkout() {
   log_info "Starting checkout"
 
   local exit_code
+  exit_code=0
+
   git reset --hard
   git clean -ffxdq
 
@@ -123,10 +125,11 @@ checkout() {
     exit_code=0
     GIT_TRACE=1 GIT_CURL_VERBOSE=1 log_and_run "${PLUGIN_DIR}/bin/timeout" "${GIT_REMOTE_TIMEOUT}" git fetch -v --no-tags origin "${BUILDKITE_BRANCH}" || exit_code=$?
     check_timeout_exit_code "${exit_code}" "${GIT_REMOTE_TIMEOUT_EXIT_CODE}"
-    GIT_TRACE=1 GIT_CURL_VERBOSE=1 log_and_run git checkout -f FETCH_HEAD
+    # TODO: should we return here, otherwise we should reset exit_code=0?
+    GIT_TRACE=1 GIT_CURL_VERBOSE=1 log_and_run git checkout -f FETCH_HEAD || exit_code=$?
   elif git cat-file -e "${BUILDKITE_COMMIT}"; then
     log_info "Checkout BUILDKITE_COMMIT=${BUILDKITE_COMMIT}"
-    GIT_TRACE=1 GIT_CURL_VERBOSE=1 log_and_run git checkout -f "${BUILDKITE_COMMIT}"
+    GIT_TRACE=1 GIT_CURL_VERBOSE=1 log_and_run git checkout -f "${BUILDKITE_COMMIT}" || exit_code=$?
   else
     # full commit sha is required
     if [[ ! "${BUILDKITE_COMMIT}" =~ [0-9a-f]{40} ]]; then
@@ -143,14 +146,15 @@ checkout() {
     # branch reference in that case.
     if [[ "${exit_code}" -eq 128 ]]; then
       log_info "Commit SHA ${BUILDKITE_COMMIT} does not exists. The ref might have been force pushed."
-      exit 116
+      return 116
     # If checking out the commit fails, it might be because the commit isn't
     # being advertised. In that case fetch the branch instead.
     elif [[ "${exit_code}" -ne 0 ]]; then
       log_info "Fail to checkout commit:${BUILDKITE_COMMIT}. Checkout branch:${BUILDKITE_BRANCH} instead."
       exit_code=0
       GIT_TRACE=1 GIT_CURL_VERBOSE=1 log_and_run "${PLUGIN_DIR}/bin/timeout" "${GIT_REMOTE_TIMEOUT}" git fetch -v --no-tags origin "${BUILDKITE_BRANCH}" || exit_code=$?
-      check_timeout_exit_code "${exit_code}" "${GIT_REMOTE_TIMEOUT_EXIT_CODE}"
+      check_timeout_exit_code "${exit_code}" "${GIT_REMOTE_TIMEOUT_EXIT_CODE}" || exit_code=$?
+      # TODO: should we return here, otherwise we should reset exit_code=0?
     fi
     # If the commit doesn't exist the ref that was pointing to it might have
     # been force pushed in the meantime. Exit with ESTALE to signify the stale
@@ -159,13 +163,18 @@ checkout() {
     GIT_TRACE=1 GIT_CURL_VERBOSE=1 log_and_run git checkout -f "${BUILDKITE_COMMIT}" || exit_code=$?
     if [[ "${exit_code}" -eq 128 ]]; then
       log_info "Commit SHA ${BUILDKITE_COMMIT} does not exists. The ref might have been force pushed."
-      exit 116
+      return 116
     elif [[ "${exit_code}" -ne 0 ]]; then
       log_info "Git returned unknown code:${exit_code}"
-      exit "${exit_code}"
+      return "${exit_code}"
     fi
   fi
-  log_info "Checkout done"
+
+  if [[ "${exit_code}" -eq 0 ]]; then
+    log_info "Checkout done"
+  fi
+
+  return "${exit_code}"
 }
 
 clean_checkout_dir() {
@@ -230,17 +239,36 @@ main() {
     echo >&2 "git-lfs not installed, skipping lfs"
   fi
 
-  initialize_local_repo
+  local max_retry=5
+  local retry=0
+  while true; do
+    initialize_local_repo
 
-  # set origin in case the repo was changed by the pre-checkout hook
-  log_info "Setting origin to ${BUILDKITE_REPO}"
-  git remote set-url origin "${BUILDKITE_REPO}"
+    # set origin in case the repo was changed by the pre-checkout hook
+    log_info "Setting origin to ${BUILDKITE_REPO}"
+    git remote set-url origin "${BUILDKITE_REPO}"
 
-  if command -v git-lfs >/dev/null; then
-    setup_git_lfs
-  fi
+    if command -v git-lfs >/dev/null; then
+      setup_git_lfs
+    fi
 
-  checkout
+    local exit_code
+    exit_code=0
+    checkout || exit_code=$?
+
+    if [[ "${exit_code}" -eq 0 ]]; then
+      break
+    fi
+
+    log_info "main:Checkout failed with error code=${exit_code}. retry=${retry}"
+    ((retry++))
+
+    if [[ "${retry}" -ge "${max_retry}" ]]; then
+      log_info "main:Maximum retry reached."
+      exit "${exit_code}"
+    fi
+
+  done
 
   if [[ "${git_lfs_skip_smudge_was_set}" == "true" ]]; then
     export GIT_LFS_SKIP_SMUDGE="${old_git_lfs_skip_smudge}"
