Update checkout

diff --git a/hooks/checkout b/hooks/checkout
--- a/hooks/checkout
+++ b/hooks/checkout
@@ -36,8 +36,8 @@ log_info() {
 }
 
 log_and_run() {
-  echo "COMMAND: $@" >> "${git_log}"
-  $@ &>> "${git_log}"
+  echo "COMMAND:" "$@" >> "${git_log}"
+  "$@" &>> "${git_log}"
 }
 
 # Checks if an env var is set
@@ -69,6 +69,15 @@ check_timeout_exit_code() {
   fi
 }
 
+exit_handler() {
+  rm "${PWD}/${checkout}"
+  if [[ $(buildkite-agent artifact upload "${git_log}") ]]; then
+    rm -rf "${git_log}"
+  else
+    log_info "Unable to upload ${git_log}."
+  fi
+}
+
 copy_checkout_from_s3() {
   local s3_url="$1"
   local checkout
@@ -86,7 +95,7 @@ copy_checkout_from_s3() {
 
   pushd .. >/dev/null
   # shellcheck disable=SC2064
-  trap "rm ${PWD}/${checkout};buildkite-agent artifact upload ${git_log} && rm -rf ${git_log}" EXIT
+  trap exit_handler EXIT
   aws s3 cp "${s3_url}/${checkout}" "${PWD}/${checkout}"
   tar -zxf "${PWD}/${checkout}"
   popd >/dev/null
@@ -110,11 +119,13 @@ checkout() {
   git config remote.origin.fetch
 
   if [[ -z "${BUILDKITE_COMMIT:-}" || "${BUILDKITE_COMMIT}" == "HEAD" ]]; then
+    log_info "Commit ID is not supplied. Fetch from HEAD."
     exit_code=0
     GIT_TRACE=1 GIT_CURL_VERBOSE=1 log_and_run "${PLUGIN_DIR}/bin/timeout" "${GIT_REMOTE_TIMEOUT}" git fetch -v --no-tags origin "${BUILDKITE_BRANCH}" || exit_code=$?
     check_timeout_exit_code "${exit_code}" "${GIT_REMOTE_TIMEOUT_EXIT_CODE}"
     GIT_TRACE=1 GIT_CURL_VERBOSE=1 log_and_run git checkout -f FETCH_HEAD
   elif git cat-file -e "${BUILDKITE_COMMIT}"; then
+    log_info "Checkout BUILDKITE_COMMIT=${BUILDKITE_COMMIT}"
     GIT_TRACE=1 GIT_CURL_VERBOSE=1 log_and_run git checkout -f "${BUILDKITE_COMMIT}"
   else
     # full commit sha is required
@@ -122,6 +133,8 @@ checkout() {
       log_info "Commit SHA ${BUILDKITE_COMMIT} is not valid. Full SHA is required."
       exit 1
     fi
+
+    log_info "Fetch BUILDKITE_COMMIT=${BUILDKITE_COMMIT}"
     exit_code=0
     GIT_TRACE=1 GIT_CURL_VERBOSE=1 log_and_run "${PLUGIN_DIR}/bin/timeout" "${GIT_REMOTE_TIMEOUT}" git fetch -v --no-tags origin "${BUILDKITE_COMMIT}" || exit_code=$?
     check_timeout_exit_code "${exit_code}" "${GIT_REMOTE_TIMEOUT_EXIT_CODE}" || exit_code=$?
@@ -129,10 +142,12 @@ checkout() {
     # been force pushed in the meantime. Exit with ESTALE to signify the stale
     # branch reference in that case.
     if [[ "${exit_code}" -eq 128 ]]; then
+      log_info "Commit SHA ${BUILDKITE_COMMIT} does not exists. The ref might have been force pushed."
       exit 116
     # If checking out the commit fails, it might be because the commit isn't
     # being advertised. In that case fetch the branch instead.
     elif [[ "${exit_code}" -ne 0 ]]; then
+      log_info "Fail to checkout commit:${BUILDKITE_COMMIT}. Checkout branch:${BUILDKITE_BRANCH} instead."
       exit_code=0
       GIT_TRACE=1 GIT_CURL_VERBOSE=1 log_and_run "${PLUGIN_DIR}/bin/timeout" "${GIT_REMOTE_TIMEOUT}" git fetch -v --no-tags origin "${BUILDKITE_BRANCH}" || exit_code=$?
       check_timeout_exit_code "${exit_code}" "${GIT_REMOTE_TIMEOUT_EXIT_CODE}"
@@ -143,8 +158,10 @@ checkout() {
     exit_code=0
     GIT_TRACE=1 GIT_CURL_VERBOSE=1 log_and_run git checkout -f "${BUILDKITE_COMMIT}" || exit_code=$?
     if [[ "${exit_code}" -eq 128 ]]; then
+      log_info "Commit SHA ${BUILDKITE_COMMIT} does not exists. The ref might have been force pushed."
       exit 116
     elif [[ "${exit_code}" -ne 0 ]]; then
+      log_info "Git returned unknown code:${exit_code}"
       exit "${exit_code}"
     fi
   fi
